name=NewTone
version=1.0.0
author=lezao
maintainer=lezao
sentence=Improved tone generation library
paragraph=Generate tones for buzzers and speakers
category=Signal Input/Output
url=https://github.com
architectures=*
